# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SyncanoChat' do

pod 'syncano-ios'
pod 'JSQMessagesViewController'  

end

target 'SyncanoChatTests' do

end

